FROM node:18.12.0-alpine

RUN mkdir -p /home/node/app/node_modules

WORKDIR /home/node/app

COPY . /home/node/app/

# RUN chown -R node:node /home/node
# RUN npm install
RUN npm install --no-optional
RUN npm install -g pm2
RUN npm run build

COPY ./.env ./build/.env

WORKDIR /home/node/app/build
# USER node

EXPOSE 3333

# CMD [ "pm2-runtime", "start", "ace", "--name=stella", "--", "serve" ]
CMD [ "pm2-runtime", "start", "server.js", "--name=ably" ]