version: '3.8'
services:
  server:
    depends_on:
      - mysqlDB
    ports:
      - 3333:3333
    build: ./
    container_name: ably_server
    restart: unless-stopped
    
    # combine below two together makes `-it` option when you use `docker exec -it`
    stdin_open: true # `-i`
    tty: true # `-t`

    networks:
      - mysql_db
  mysqlDB:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - .env
    container_name: mysql_db
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=new1234!
      - MYSQL_PASSWORD=new1234!
      - MYSQL_USER=ably
      - MYSQL_DATABASE=ably
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql  # -v option
    networks:
      - mysql_db
volumes:
    db:
networks:
    mysql_db:
      driver: bridge
